name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/yuanhaoji/sparkml
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Unit test with Maven
        run: mvn --batch-mode --update-snapshots -e -V clean test

      - name: Upload unit test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: ./**/target/surefire-reports/
          if-no-files-found: ignore

      - name: Upload integration test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failsafe-reports
          path: ./**/target/failsafe-reports/
          if-no-files-found: ignore
